export enum ROLES  {
  ADMIN="ADMIN",
  USER="USER"
}
export enum PERMISSIONS {
  VIEW_DASHBOARD = "VIEW_DASHBOARD",

  CREATE_BLOG = "CREATE_BLOG",
  EDIT_BLOG = "EDIT_BLOG",
  DELETE_BLOG = "DELETE_BLOG",

  VIEW_USERS = "VIEW_USERS",
   EDIT_USER = "EDIT_USER",
  DELETE_USER = "DELETE_USER",
  VIEW_PROFILE = "VIEW_PROFILES",

  FOLLOW_USERS = "FOLLOW_USERS",
  UNFOLLOW_USERS = "UNFOLLOW_USERS",
  VIEW_BLOG = "VIEW_BLOG",
  COMMENT_BLOG = "COMMENT_BLOG",
  EDIT_COMMENT = "EDIT_COMMENT",
  DELETE_COMMENT = "DELETE_COMMENT",

  LIKE_BLOG = "LIKE_BLOG",

  VIEW_ADMIN_DASHBOARD = "VIEW_ADMIN_DASHBOARD",
  VIEW_ANALYTICS = "VIEW_ANALYTICS",
  FOLLOW_REQUEST="FOLLOW_REQUEST"

}

export const ROLE_PERMISSIONS:Record<ROLES , string[]> = {
  [ROLES.USER]: [
    // PERMISSIONS.VIEW_DASHBOARD,
    // PERMISSIONS.VIEW_BLOG,
    PERMISSIONS.CREATE_BLOG,
    PERMISSIONS.EDIT_BLOG,
    PERMISSIONS.VIEW_BLOG,
    PERMISSIONS.DELETE_BLOG,
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.EDIT_USER,
    PERMISSIONS.DELETE_USER,
    PERMISSIONS.VIEW_PROFILE,
    PERMISSIONS.FOLLOW_USERS,
    PERMISSIONS.UNFOLLOW_USERS,
    PERMISSIONS.COMMENT_BLOG,
    PERMISSIONS.EDIT_COMMENT,
    PERMISSIONS.DELETE_COMMENT,

    PERMISSIONS.LIKE_BLOG,
    PERMISSIONS.FOLLOW_REQUEST

  ],

  [ROLES.ADMIN]: [
    PERMISSIONS.VIEW_ADMIN_DASHBOARD,
    // PERMISSIONS.VIEW_BLOG,
    PERMISSIONS.DELETE_USER,
        PERMISSIONS.VIEW_BLOG,

    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.VIEW_PROFILE,
    PERMISSIONS.DELETE_BLOG,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.EDIT_COMMENT,
    PERMISSIONS.DELETE_COMMENT,

  ],
};