export type Role = "ADMIN" | "USER";

export const PERMISSIONS = {
  VIEW_DASHBOARD : "VIEW_DASHBOARD",

  CREATE_BLOG : "CREATE_BLOG",
  EDIT_BLOG :"EDIT_BLOG",
  DELETE_BLOG : "DELETE_BLOG",

  VIEW_USERS :"VIEW_USERS",
   EDIT_USER : "EDIT_USER",
  DELETE_USER : "DELETE_USER",
  VIEW_PROFILE : "VIEW_PROFILES",

  FOLLOW_USERS : "FOLLOW_USERS",
  UNFOLLOW_USERS : "UNFOLLOW_USERS",
  VIEW_BLOG : "VIEW_BLOG",
  COMMENT_BLOG : "COMMENT_BLOG",
  EDIT_COMMENT : "EDIT_COMMENT",
  DELETE_COMMENT : "DELETE_COMMENT",

  LIKE_BLOG : "LIKE_BLOG",

  VIEW_ADMIN_DASHBOARD : "VIEW_ADMIN_DASHBOARD",
  VIEW_ANALYTICS : "VIEW_ANALYTICS",
  FOLLOW_REQUEST:"FOLLOW_REQUEST"

}